# Generated by Django 4.1 on 2022-10-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardsApp', '0007_alter_boards_status'),
        ('workSpacesApp', '0006_alter_workspaces_status'),
        ('commentApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
