# Generated by Django 4.1 on 2022-08-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
        ('commentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin_users', models.ManyToManyField(related_name='cards_adm', to='userApp.customuser')),
                ('comments', models.ManyToManyField(related_name='cards_comment', to='commentApp.comment')),
                ('users', models.ManyToManyField(related_name='cards_users', to='userApp.customuser')),
            ],
        ),
    ]
