# Generated by Django 4.1 on 2022-10-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusboards',
            name='icon',
            field=models.FileField(upload_to='data/statusBoards/icons'),
        ),
        migrations.AlterField(
            model_name='statuswk',
            name='icon',
            field=models.FileField(upload_to='data/statusBoards/icons'),
        ),
    ]
