# Generated by Django 4.1 on 2022-08-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
        ('boardsApp', '0001_initial'),
        ('commentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_title', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(default='', upload_to='')),
                ('type', models.CharField(choices=[(1, 'Малый Бизнес'), (2, 'Управление персоналом'), (3, 'Операции'), (4, 'Продажи CRM'), (5, 'Маркетинг'), (6, 'Инженерия IT'), (7, 'Образование'), (8, 'Другое')], max_length=100)),
                ('web_site', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('join_link', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField()),
                ('admin_users', models.ManyToManyField(related_name='workspaces_adm', to='userApp.customuser')),
                ('boards', models.ManyToManyField(related_name='workspaces_boards', to='boardsApp.boards')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentApp.status')),
                ('users', models.ManyToManyField(related_name='workspaces_users', to='userApp.customuser')),
            ],
        ),
    ]
