# Generated by Django 4.1 on 2022-08-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workSpacesApp', '0002_alter_workspaces_boards_alter_workspaces_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaces',
            name='type',
            field=models.IntegerField(choices=[(1, 'Малый Бизнес'), (2, 'Управление персоналом'), (3, 'Операции'), (4, 'Продажи CRM'), (5, 'Маркетинг'), (6, 'Инженерия IT'), (7, 'Образование'), (8, 'Другое')], max_length=255),
        ),
    ]
