# Generated by Django 4.1 on 2022-08-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workSpacesApp', '0004_alter_workspaces_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaces',
            name='short_title',
        ),
    ]
