# Generated by Django 4.1 on 2022-10-04 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('workSpacesApp', '0005_remove_workspaces_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaces',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.statuswk'),
        ),
    ]
