# Generated by Django 4.1 on 2022-08-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
        ('boardsApp', '0001_initial'),
        ('columnApp', '0001_initial'),
        ('commentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='admin_users',
            field=models.ManyToManyField(related_name='boards_adm', to='userApp.customuser'),
        ),
        migrations.AddField(
            model_name='boards',
            name='column',
            field=models.ManyToManyField(related_name='boards_column', to='columnApp.column'),
        ),
        migrations.AddField(
            model_name='boards',
            name='private_users',
            field=models.ManyToManyField(related_name='boards_privat', to='userApp.customuser'),
        ),
        migrations.AddField(
            model_name='boards',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentApp.status'),
        ),
        migrations.AddField(
            model_name='boards',
            name='users',
            field=models.ManyToManyField(related_name='boards_users', to='userApp.customuser'),
        ),
    ]
