# Generated by Django 4.1 on 2022-08-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workSpacesApp', '0004_alter_workspaces_type'),
        ('boardsApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='private_users',
        ),
        migrations.AddField(
            model_name='boards',
            name='workspace',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='boards_privat', to='workSpacesApp.workspaces'),
            preserve_default=False,
        ),
    ]
