# Generated by Django 4.1 on 2022-08-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_alter_customuser_favorites_boards'),
        ('columnApp', '0001_initial'),
        ('boardsApp', '0003_remove_boards_private_users_boards_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='background',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='boards',
            name='column',
            field=models.ManyToManyField(blank=True, related_name='boards_column', to='columnApp.column'),
        ),
        migrations.AlterField(
            model_name='boards',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='boards_users', to='userApp.customuser'),
        ),
    ]
