# Generated by Django 4.1 on 2022-09-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardsApp', '0005_remove_boards_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='slug',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
