# Generated by Django 4.1 on 2022-08-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=123, max_length=254),
            preserve_default=False,
        ),
    ]
