# Generated by Django 4.1 on 2022-08-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardsApp', '0002_initial'),
        ('userApp', '0002_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorites_boards',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to='boardsApp.boards'),
        ),
    ]
