# Generated by Django 4.1 on 2022-08-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardsApp', '0002_initial'),
        ('userApp', '0003_remove_customuser_email_remove_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorites_boards',
            field=models.ManyToManyField(related_name='user', to='boardsApp.boards'),
        ),
    ]
