# Generated by Django 4.1 on 2022-08-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardsApp', '0003_remove_boards_private_users_boards_workspace'),
        ('userApp', '0004_alter_customuser_favorites_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorites_boards',
            field=models.ManyToManyField(blank=True, related_name='user', to='boardsApp.boards'),
        ),
    ]
